apiVersion: batch/v1
kind: Job
metadata:
  name: hello
spec:
  template:
    # This is the pod template
    spec:
      containers:
      - name: hello
        image: djgagner/git-pipeline-best-practices
        command: ['sh', '-c', 'aws --version']
      restartPolicy: OnFailure