---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: java
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: java
        use-fargate: "yes"
    spec:
      containers:
      - image: 007156912793.dkr.ecr.us-east-1.amazonaws.com/kubernetes-lab
        imagePullPolicy: Always
        name: java
        ports:
        - containerPort: 6789
---
apiVersion: v1
kind: Service
metadata:
  name: java
spec:
  ports:
    - port: 6789
      targetPort: 6789
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: java